version: "3.8"
services:
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:v2.12.14
    ports:
      - 3005:3000
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${ADMIN}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ACCESS_KEY}
      ANSIBLE_HOST_KEY_CHECKING: false
    restart: unless-stopped
    networks:
      - frontend
      - backend
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore
      - /opt/homelab:/opt/homelab
volumes:
  semaphore_data: null
  semaphore_config: null
  semaphore_tmp: null
networks:
  frontend:
    external: true
  backend:
    external: true
