version: "3.8"
services:
  # Fix cloudflare ddos protection issues
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Oslo
    ports:
      - ${PORT:-8191}:8191
    restart: unless-stopped
  
  # Handle media requests 
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/appdata/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
        - frontend
        - backend
  
  # Index proxy / scanner
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  # Book manager
  readarr:
    # books
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/appdata/readarr:/config
      - /mnt/media/books:/books #optional
      - /mnt/downloads/:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  
  # Movie manager
  radarr:
    # Movies
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/media/movies:/movies #optional
      - /mnt/downloads/:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  
  # Serie manager
  sonarr:
    # Series
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/appdata/sonarr-anime:/config
      - /mnt/media/series/anime:/anime #optional
      - /mnt/media/series/tv:/tv #optional
      - /mnt/downloads/:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  
  # Media compression
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=homelab-tdarr-internal
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/appdata/tdarr/server:/app/server
      - /opt/appdata/tdarr/configs:/app/configs
      - /opt/appdata/tdarr/logs:/app/logs
      - /mnt/media:/media
      - /opt/appdata/tdarr-transcode:/transcode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
networks:
  backend:
    external: true
  frontend:
    external: true
  default:
    name: backend
    external: true
