version: "3.8"
services:
  traefik:
    image: docker.io/library/traefik:v3.3.3
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      # <--
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - /opt/appdata/traefik/acme.json:/acme.json
      - /opt/appdata/traefik/data/certs/:/var/traefik/certs/:rw
      - /opt/appdata/traefik/origin:/certs
    environment:
      - CF_DNS_API_TOKEN=${DNS_TOKEN} # <-- Change this to your Cloudflare API Token
    networks:
      - frontend
    restart: unless-stopped
  # app:
  #   image: jc21/nginx-proxy-manager:latest
  #   container_name: nginx-proxy-manager
  #   restart: unless-stopped
  #   ports:
  #     # These ports are in format <host-port>:<container-port>
  #     - 180:80 # Public HTTP Port
  #     - 1443:443 # Public HTTPS Port
  #     - 181:81 # Admin Web Port
  #     # Add any other Stream port you want to expose
  #     # - '21:21' # FTP
  #
  #     # environment:
  #     # Uncomment this if you want to change the location of
  #     # the SQLite DB file within the container
  #     # DB_SQLITE_FILE: "/data/database.sqlite"
  #
  #     # Uncomment this if IPv6 is not enabled on your host
  #     # DISABLE_IPV6: 'true'
  #   volumes:
  #     - /opt/appdata/NginxProxyManager:/data
  #     - /opt/appdata/NginxProxyManager/letsencrypt:/etc/letsencrypt
  #   networks:
  #     - homelab

networks:
  backend:
    external: true
  frontend:
    external: true
