version: "3.8"
services:
  traefik:
    image: docker.io/library/traefik:v3.3.3
    container_name: traefik
    ports:
      - 180:80
      - 1443:443
      - 1443:443/tcp
      - 1443:443/udp
      - 8080:8080
      # <--
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/fast/appdata/traefik/data/traefik.yml:/traefik.yml:ro # needs to be manually created
      - /mnt/fast/appdata/traefik/data/acme.json:/acme.json # needs to be manually created
      - /mnt/fast/appdata/traefik/data/config.yml:/config.yml:ro
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_api_token
      - ${TRAEFIK_DASHBOARD_CREDENTIALS}
      - DOMAIN_NAME=${DOMAIN_NAME}
    secrets:
      - cf_api_token
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"

      # - "traefik.http.routers.drouter.entrypoints=http"
      # - "traefik.http.routers.drouter.rule=Host(`traefik.${DOMAIN_NAME}`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      # - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      # - "traefik.http.routers.d-secure-router.rule=Host(`traefik.${DOMAIN_NAME}`)"
      # - "traefik.http.routers.d-secure-router.middlewares=traefik-auth"
      # - "traefik.http.routers.d-secure-router.tls=true"
      # - "traefik.http.routers.d-secure-router.service=api@internal"
    restart: unless-stopped

secrets:
  cf_api_token:
    file: /mnt/fast/appdata/traefik/cf_api_token.txt

networks:
  backend:
    external: true
  frontend:
    external: true
