---
- name: Update apt systems
  hosts: ubuntu
  vars:
    notify_discord_webhook_id: ''
    notify_discord_webhook_token: ''

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      become: true
      ansible.builtin.apt:
        upgrade: dist

    - name: Check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required

    - name: Report if reboot is required
      community.general.discord:
        webhook_id: "{{ notify_discord_webhook_id }}"
        webhook_token: "{{ notify_discord_webhook_token }}"
        content: "A server needs restarting"
      when: reboot_required.stat.exists
      - name: Send a message to the Discord channel
  
