---
- name: Update apt systems
  hosts: all

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      become: true
      ansible.builtin.apt:
        upgrade: safe

    - name: Check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required

    - name: Report if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists
