version: "3.8"
services:
  # Plex media streaming platform
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - VERSION=docker
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /opt/appdata/plex:/config
      - /dev/shm:/transcode
      - /mnt/media/series:/tv
      - /mnt/media/movies:/movies
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    restart: unless-stopped
  # Stats for plex
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /opt/appdata/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
networks:
  default:
    name: homelab
    external: true
x-dockge:
  urls:
    - http://192.168.1.50:32400
    - https://app.plex.tv
    - http://192.168.1.50:8181
