version: "3.3"
services:
  delugevpn:
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 8118:8118
      - 9118:9118
      - 58846:58846
      - 58946:58946
      - 58946:58946/udp
    container_name: delugevpn
    volumes:
      - /mnt/downloads:/downloads
      - /opt/appdata/delugevpn:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${PIA_USER}
      - VPN_PASS=${PIA_PASSWORD}
      - VPN_PROV=pia
      - VPN_CLIENT=openvpn
      - ENABLE_STARTUP_SCRIPTS=no
      - ENABLE_PRIVOXY=yes
      - STRICT_PORT_FORWARD=yes
      - USERSPACE_WIREGUARD=no
      - ENABLE_SOCKS=yes
      - SOCKS_USER=admin
      - SOCKS_PASS=socks
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - DELUGE_DAEMON_LOG_LEVEL=info
      - DELUGE_WEB_LOG_LEVEL=info
      - DELUGE_ENABLE_WEBUI_PASSWORD=yes
      - VPN_INPUT_PORTS=1234
      - VPN_OUTPUT_PORTS=5678
      - DEBUG=false
      - UMASK=000
      - PUID=0
      - PGID=0
      - UID=1000
      - GID=1000
    image: binhex/arch-delugevpn
networks:
  default:
    name: homelab
    external: true
x-dockge:
  urls:
    - http://192.168.1.50:8112
    - https://deluge.clenchedgaming.com
