version: "3.8"
services:
  tailscale:
    image: tailscale/tailscale:latest
    hostname: ${TS_HOSTNAME}
    environment:
      - TS_AUTHKEY=${AUTHKEY}}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVER_CONFIG=/config/ts-serve.json
      - TS_USERSPACE=false
    volumes:
      - ts_state:/var/lib/tailscale
      - ./config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module 
    restart: unless-stopped
networks:
  default: 
    name: homelab
    external: true
volumes:
  ts_state:
  # nginx:
  #   image: nginx
  #   depends_on:
  #     - tailscale-nginx
  #   network_mode: service:tailscale-nginx
